include:
  - core/tools/create-mock.yaml
  - core/tools/create-chat-message.yaml
  - core/tools/create-document.yaml
  - core/tools/switch-target.yaml
  - examples/examples-workspace.yaml

pipelines:
  - name: human_in_the_loop_example
    title: "Example 7: Human-in-the-Loop Workflow"
    type: root
    workspace: examples
    sequence:
      - workflow: changelog_review

workflows:
  - name: changelog_review
    type: stateMachine
    transitions:
      - name: create_draft         # Step 1: Generate initial content draft
        from: start
        to: draft_created
        call:
          - tool: create_mock
            arguments:
              input: 'commit hash'
              output: |
                # Changelog - Version 2.4.1
  
                  **Release Date:** September 9, 2025
                
                ## Bug Fixes
                
                - **Fixed memory leak in image processing module** - Resolved issue causing gradual performance degradation during batch operations
                - **Corrected timezone display bug** - User timestamps now properly reflect local timezone settings
                - **Resolved crash on startup** - Fixed null pointer exception affecting users with custom themes
                - **Fixed search functionality** - Special characters in queries no longer break search results
                - **Improved error handling** - Network timeout errors now display user-friendly messages instead of technical codes
                
                ## Minor Improvements
                
                - Enhanced loading spinner animations
                - Updated dependency libraries to latest stable versions
                - Optimized database query performance by 15%
            as: DRAFT_CONTENT

          - tool: create_chat_message
            arguments:
              role: 'assistant'
              content: 'Changelog was generated and is ready for your review.'

      - name: show_approval_form    # Step 2: Present draft to user for approval
        from: draft_created
        to: waiting_for_approval
        call:
          - tool: create_document
            arguments:
              document: approval_form
              content:
                draft_content: ${ DRAFT_CONTENT }
                approved: false
                feedback: ""

      - name: process_approval       # Step 3: Handle user's approval decision
        from: waiting_for_approval
        to:
          - approved
          - needs_revision
        when: manual                # Wait for user interaction
        call:
          - tool: create_mock
            arguments:
              input: ${ transition.payload }
              output: ${ transition.payload.approved }
            as: USER_DECISION

          - tool: switch_target
            arguments:
              target: "{{#if (eq USER_DECISION true)}}approved{{else}}needs_revision{{/if}}"

      # Approval path
      - name: finalize_content       # Handle approved content
        from: approved
        to: end
        call:
          - tool: create_mock
            arguments:
              input: ${ DRAFT_CONTENT }
              output: 'Change is promoted to ready for publishing'
            as: PUBLISH_RESULT

          - tool: create_chat_message
            arguments:
              role: 'assistant'
              content: |
                ✅ Changelog approved.
                
                {{ PUBLISH_RESULT }}

      # Revision path
      - name: handle_revision        # Handle revision requests
        from: needs_revision
        to: draft_created            # Return to draft creation for revision
        call:
          - tool: create_chat_message
            arguments:
              role: 'assistant'
              content: '📝 Revision requested. Generating updated draft with your feedback...'

          - tool: create_mock
            arguments:
              input: ${ DRAFT_CONTENT }
              output: |
                # Release Notes - v2.4.1
                  *September 9, 2025*
                
                ## Critical Fixes
                - **Memory leak resolved** - Fixed performance degradation in image batch processing
                - **Startup crash eliminated** - Resolved null pointer exception with custom themes
                - **Search now handles special characters** - No more broken queries with symbols
                - **Timezone display corrected** - Timestamps now reflect proper local time
                - **Better error messages** - Clear notifications replace cryptic network codes
                
                ## ⚡ Performance
                - Database queries optimized (15% faster)
                - Updated core dependencies
                - Smoother loading animations
            as: DRAFT_CONTENT

documents:
  - name: approval_form
    schema:
      type: object
      properties:
        draft_content:
          type: string
        approved:
          type: boolean
        feedback:
          type: string
      required:
        - draft_content
        - approved
    ui:
      properties:
        draft_content:
          widget: textarea-expand
          title: "Draft Content"
          readonly: true
        approved:
          widget: switch
          title: "Approve"
        feedback:
          widget: textarea
          title: "Feedback (optional)"
          placeholder: "Provide feedback for revisions..."
      order:
        - draft_content
        - feedback
        - approved
      buttons:
        - transition: process_approval
          label: "Submit Decision"
          enabledWhen:
            - waiting_for_approval
