include:
  - core/tools/create-mock.yaml
  - core/tools/create-chat-message.yaml
  - core/tools/create-document.yaml
  - core/tools/switch-target.yaml
  - examples/examples-workspace.yaml

pipelines:
  - name: human_in_the_loop_example
    title: "Example 7: Human-in-the-Loop Workflow"
    type: root
    workspace: examples
    sequence:
      - workflow: blog_post_review

workflows:
  - name: blog_post_review
    type: stateMachine
    transitions:
      - name: create_draft         # Step 1: Generate initial content draft
        from: start
        to: draft_created
        call:
          - tool: create_mock
            arguments:
              input: 'blog post about renewable energy'
              output: |
                # The Future of Renewable Energy

                Renewable energy sources are becoming increasingly important as we work toward a sustainable future. Solar and wind power have seen dramatic cost reductions, making them competitive with traditional fossil fuels.

                Key benefits include:
                - Reduced carbon emissions
                - Energy independence
                - Long-term cost savings

                The transition to renewable energy represents one of the most significant opportunities of our time.
            as: DRAFT_CONTENT

          - tool: create_chat_message
            arguments:
              role: 'assistant'
              content: 'Draft content has been generated and is ready for your review.'

      - name: show_approval_form    # Step 2: Present draft to user for approval
        from: draft_created
        to: waiting_for_approval
        call:
          - tool: create_document
            arguments:
              document: approval_form
              content:
                draft_content: ${ DRAFT_CONTENT }
                approved: false
                feedback: ""

      - name: process_approval       # Step 3: Handle user's approval decision
        from: waiting_for_approval
        to:
          - approved
          - needs_revision
        when: manual                # Wait for user interaction
        call:
          - tool: create_mock
            arguments:
              input: ${ transition.payload }
              output: ${ transition.payload.approved }
            as: USER_DECISION

          - tool: switch_target
            arguments:
              target: "{{#if (eq USER_DECISION true)}}approved{{else}}needs_revision{{/if}}"

      # Approval path
      - name: finalize_content       # Handle approved content
        from: approved
        to: end
        call:
          - tool: create_mock
            arguments:
              input: ${ DRAFT_CONTENT }
              output: 'Content published successfully to blog.example.com'
            as: PUBLISH_RESULT

          - tool: create_chat_message
            arguments:
              role: 'assistant'
              content: |
                ✅ Content approved and published!
                
                {{ PUBLISH_RESULT }}

      # Revision path
      - name: handle_revision        # Handle revision requests
        from: needs_revision
        to: draft_created            # Return to draft creation for revision
        call:
          - tool: create_chat_message
            arguments:
              role: 'assistant'
              content: '📝 Revision requested. Generating updated draft with your feedback...'

          - tool: create_mock
            arguments:
              input: ${ DRAFT_CONTENT }
              output: |
                # The Future of Renewable Energy (Revised)

                Renewable energy sources are rapidly transforming our global energy landscape. Solar and wind power have experienced unprecedented cost reductions, making them not just environmentally responsible but economically superior to traditional fossil fuels.

                Key benefits include:
                - Significant reduction in carbon emissions
                - Enhanced energy independence and security
                - Substantial long-term cost savings
                - Job creation in emerging green industries

                The transition to renewable energy represents the most transformative opportunity of our generation, offering both environmental and economic advantages.
            as: DRAFT_CONTENT

documents:
  - name: approval_form
    schema:
      type: object
      properties:
        draft_content:
          type: string
        approved:
          type: boolean
        feedback:
          type: string
      required:
        - draft_content
        - approved
    ui:
      properties:
        draft_content:
          widget: textarea-expand
          title: "Draft Content"
          readonly: true
        approved:
          widget: switch
          title: "Approve"
        feedback:
          widget: textarea
          title: "Feedback (optional)"
          placeholder: "Provide feedback for revisions..."
      order:
        - draft_content
        - feedback
        - approved
      buttons:
        - transition: process_approval
          label: "Submit Decision"
          enabledWhen:
            - waiting_for_approval
