include:
  - core/tools/create-mock.yaml
  - core/tools/create-chat-message.yaml
  - core/tools/create-error-message.yaml
  - core/tools/create-document.yaml
  - examples/examples-workspace.yaml

pipelines:
  - name: error_handling_example
    title: "Example 5: Error Handling"
    type: root
    workspace: examples
    sequence:
      - workflow: failing_workflow

workflows:
  - name: failing_workflow
    type: stateMachine
    transitions:
      - name: call_api               # Step 1: Attempt to call external API
        from: start
        to:
          - api_success
          - api_failed
        onError: api_failed          # Go here if an error occurs
        call:
          - tool: create_mock
            arguments:
              input: 'weather for San Francisco'
              error: 'API service unavailable: 503 Service Temporarily Unavailable'  # Throw an error for demonstration
            as: API_RESULT

          - tool: create_chat_message   # This tool call will not execute, since an error occurred before
            arguments:
              role: 'assistant'
              content: 'Weather data retrieved: {{ API_RESULT }}'

      # Success path
      - name: display_result         # Normal completion when API succeeds
        from: api_success
        to: end
        call:
          - tool: create_chat_message
            arguments:
              role: 'assistant'
              content: '✅ API lookup completed successfully!'

      # Error handling path
      - name: handle_api_error        # Handle API failure
        from: api_failed
        to: waiting_for_retry
        call:
          - tool: create_error_message
            arguments:
              message: ${ data.call_api.error }     # Access error from previous transition: data.<transition>.error

          - tool: create_document
            arguments:
              document: retry_form
              content:
                message: "API call failed. Click 'Retry' to attempt the request again."
                timestamp: "{{ currentDate }}"

      # Manual recovery transition
      - name: retry_api_call          # User can manually retry the API call
        from: waiting_for_retry
        to: start                   # Return to start to retry the original API call
        when: manual                # Wait for user interaction

documents:
  - name: retry_form
    schema:
      type: object
      properties:
        message:
          type: string
        timestamp:
          type: string
    ui:
      properties:
        message:
          title: "Status"
          readonly: true
        timestamp:
          title: "Error Time"
          readonly: true
      buttons:
        - transition: retry_api_call
          label: "Retry"
          enabledWhen:
            - waiting_for_retry
