include:
  - core/tools/create-mock.yaml
  - core/tools/create-chat-message.yaml

pipelines:
  - name: sequence_example
    title: "Example 1: Pipeline Sequence"
    type: root
    workspace: examples
    sequence:
      - workflow: research_topic      # Step 1: Research
      - workflow: write_content       # Step 2: Write content
      - workflow: publish_content     # Step 3: Publish

workflows:
  - name: research_topic
    title: 'Research'
    type: stateMachine
    transitions:
      - name: research_topic
        from: start
        to: research_finished
        call:
          - tool: create_mock   # A mock tool call returning the research result
            arguments:
              input: 'AI trends 2025'
              output: 'Key AI trends include: agentic AI systems, reasoning models, and AI-powered robotics.'
            exportContext: RESEARCH_RESULT
      - name: show_results
        from: research_finished
        to: end
        call:
          - tool: create_chat_message    # Display the results in the chat
            arguments:
              role: 'assistant'
              content: ${ context.variables.RESEARCH_RESULT }

  - name: write_content
    title: "Write Content"
    type: stateMachine
    transitions:
      - name: write_content
        from: start
        to: content_created
        call:
          - tool: create_mock   # A mock tool call returning the created content
            arguments:
              input: ${ context.variables.RESEARCH_RESULT }
              output: |
                # Top AI Trends in 2025 
                Here are the key trends defining this year...
            exportContext: CREATED_CONTENT
      - name: show_results
        from: content_created
        to: end
        call:
          - tool: create_chat_message    # Display the content in the chat
            arguments:
              role: 'assistant'
              content: ${ context.variables.CREATED_CONTENT }

  - name: publish_content
    title: "Publish"
    type: stateMachine
    transitions:
      - name: publish_content
        from: start
        to: published
        call:
          - tool: create_mock   # A mock tool call returning a success message
            arguments:
              input: ${ context.variables.CREATED_CONTENT }
              output: 'Blog post "Top AI Trends in 2025" published successfully to blog.example.com'
            exportVariable: SUCCESS_MESSAGE
      - name: show_results
        from: published
        to: end
        call:
          - tool: create_chat_message    # Display the success message in the chat
            arguments:
              role: 'assistant'
              content: ${ SUCCESS_MESSAGE }