include:
  - core/tools/create-chat-message.yaml
  - core/tools/create-document.yaml
  - core/tools/update-document.yaml
  - core/tools/load-document.yaml

documents:
  - name: customer_profile
    description: "Customer information and preferences"
    schema:
      type: object
      properties:
        name:
          title: "Name"
          type: string
        email:
          title: "Email"
          type: string
          format: email
        status:
          title: "Status"
          type: string
          enum: ["prospect", "active", "inactive"]
        metadata:
          title: "Metadata"
          type: object
          properties:
            source:
              title: "Source"
              type: string
      required:
        - name
        - email
        - status
    content:
      status: "prospect"
      metadata:
        source: "unknown"
    ui:
      order:
        - name
        - email
        - status
        - metadata

pipelines:
  - name: documents_example
    title: "Example 6: Working with Documents"
    type: root
    workspace: examples
    sequence:
      - workflow: create_profile
      - workflow: update_profile

workflows:
  - name: create_profile
    title: "Create Customer Profile"
    type: stateMachine
    transitions:

      # Create the initial document
      - name: create_initial_profile
        from: start
        to: profile_created
        call:
          - tool: create_document
            arguments:
              document: customer_profile        # Reference to document template
              content:                          # Content object to merge with template
                name: "John Smith"
                email: "john.smith@example.com" # Override template default
                metadata:
                  source: "website_signup"
            exportVariable: CREATED_PROFILE     # Store document reference

      # Update a document from the same workflow
      - name: update_status
        from: profile_created
        to: profile_updated
        call:
          - tool: load_document
            arguments:
              where:
                name: customer_profile
            exportVariable: LOADED_PROFILE
          - tool: update_document
            arguments:
              id: ${ LOADED_PROFILE.id }    # Use ID from loaded document
              content:
                status: "active"            # Update status
            exportVariable: UPDATED_PROFILE

      - name: log_result
        from: profile_updated
        to: end
        call:
          - tool: create_chat_message
            arguments:
              role: assistant
              content: |
                ✅ Customer profile created successfully!

                **Profile Details:**
                - Name: {{ UPDATED_PROFILE.content.name }}
                - Email: {{ UPDATED_PROFILE.content.email }}
                - Status: {{ UPDATED_PROFILE.content.status }}

  - name: update_profile
    title: "Update Customer Profile"
    type: stateMachine
    transitions:

      # We cannot update a document from another workflow
      # So we create a new document instead of updating it
      - name: update_profile
        from: start
        to: profile_updated
        call:
          - tool: load_document
            arguments:
              where:
                name: customer_profile
            exportVariable: LOADED_PROFILE
          - tool: create_document
            arguments:
              document: customer_profile
              content:    # Content object to merge with template
                name: ${ LOADED_PROFILE.content.name }
                email: ${ LOADED_PROFILE.content.email }
                metadata:
                  source: ${ LOADED_PROFILE.content.metadata.source }
                status: 'inactive'
            exportVariable: UPDATED_PROFILE

      - name: log_result
        from: profile_updated
        to: end
        call:
          - tool: create_chat_message
            arguments:
              role: assistant
              content: |
                ✅ Customer profile updated successfully!

                **Updated Information:**
                - Status: {{ UPDATED_PROFILE.content.status }}
