documents:
  - name: examples_predefinedWorkflow_userInputDocument
    schema:
      type: object
      properties:
        text:
          type: string
    ui:
      properties:
        text:
          widget: textarea
      buttons:
        - transition: addUserInput
          label: "Submit"
    content:
      text: ""

workflows:
  - name: examples_predefinedWorkflow_workflow
    title: "Analyse and Improve Text"
    type: stateMachine
    transitions:

      - name: requestUserInput
        from: start
        to: waitingForUser
        call:
          - tool: core_createChatMessage
            arguments:
              role: assistant
              content: "This simple workflow example takes user-provided text, analyzes it for issues, and then improves it based on the analysis."
          - tool: core_createDocument
            arguments:
              document: examples_predefinedWorkflow_userInputDocument
              content:
                text: "Me and my friend goes to the store yesterday we buy some stuff for the party but we forgot to get drinks so we had to went back again it was really annoying."

      - name: addUserInput
        from: waitingForUser
        to: userInputAdded
        when: manual
        call:
          - tool: core_createDocument
            arguments:
              document: examples_predefinedWorkflow_userInputDocument
              content: ${{ transition.payload }}
            exportVariable: USER_INPUT_DOCUMENT

      - name: analyse
        from: userInputAdded
        to: inputAnalysed
        call:
          - tool: examples_predefinedWorkflow_analyseText
            exportVariable: ANALYSIS

      - name: addAnalysis
        from: inputAnalysed
        to: analysisAdded
        call:
          - tool: core_createPlainMessage
            arguments:
              title: "Analysis"
              content: ${{ ANALYSIS.response.data.content }}

      - name: improve
        from: analysisAdded
        to: improved
        call:
          - tool: examples_predefinedWorkflow_improveText
            exportVariable: IMPROVED_TEXT

      - name: addImprovedText
        from: improved
        to: improvedTextAdded
        call:
          - tool: core_createPlainMessage
            arguments:
              title: "Improved Text"
              content: ${{ IMPROVED_TEXT.response.data.content }}

tools:
  - name: examples_predefinedWorkflow_analyseText
    execute:
      service: LlmCompletionService
      arguments:
        llm:
          envApiKey: OPENAI_KEY
          model: gpt-4o
        messages:
          - role: system
            content: |
              You are a content analyst. Analyze the provided text and identify:
              1. Grammar and spelling issues
              2. Clarity problems
              3. Tone inconsistencies
              4. Structural improvements needed
              
              Provide your analysis in a structured format with specific recommendations.
          - role: user
            content: |
              Please analyze this text: 
              ${{ USER_INPUT_DOCUMENT.text }}

  - name: examples_predefinedWorkflow_improveText
    execute:
      service: LlmCompletionService
      arguments:
        llm:
          envApiKey: OPENAI_KEY
          model: gpt-4o
        messages:
          - role: system
            content: |
              You are a professional editor. Based on the analysis provided, improve the original text by:
              1. Fixing grammar and spelling errors
              2. Enhancing clarity and readability
              3. Maintaining the original meaning and intent
              4. Improving overall structure and flow
              
              Return only the improved version of the text.
          - role: user
            content: |
              Original text:
              ${{ USER_INPUT_DOCUMENT.text }}

              Analysis and recommendations:
              ${{ ANALYSIS.response.data }}
                
              Please provide an improved version of the original text based on this analysis.

pipelines:
  - name: examples_predefinedWorkflow
    title: "Predefined Workflow Example"
    workspace: examples
    type: root
    sequence:
      - workflow: examples_predefinedWorkflow_workflow
