services:
  redis:
    image: redis:8.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - monorepo-network

  postgres:
    image: postgres:16.9-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - monorepo-network

  websocket-server:
    image: jakobklippel/loopstack-websocket-server:latest
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_PORT=3001
      - CORS_ORIGIN=localhost
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    networks:
      - monorepo-network

  react-app:
    image: jakobklippel/loopstack-react-app:latest
    ports:
      - "3080:3000"
    depends_on:
      - websocket-server
    restart: unless-stopped
    networks:
      - monorepo-network

networks:
  monorepo-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis-data:
    driver: local
