workflows:
  - name: llm_structuredResponseReasonOutputReflectionTemplate
    type: stateMachine
    transitions:
      - name: prepare
        from: start
        to:
          - prepared
          - error
        when: onEntry

      - name: start-conditional
        from: prepared
        to:
          - starting
          - skipping
        when: onEntry

      - name: start
        from: starting
        to: started
        when: onEntry

      - name: skip
        from: skipping
        to: end
        when: onEntry

      - name: CreateOutputTemplate
        from: started
        to: output-template-created
        when: onEntry
        call:
          - tool: llm_createOutputTemplate
            exportVariable: OUTPUT_TEMPLATE

      - name: create-messages
        from: output-template-created
        to: messages-prepared
        when: onEntry

      - name: execute-prompt
        from: messages-prepared
        to:
          - prompt-executed
          - error
        when: onEntry
        call:
          - tool: llm_executePrompt
            exportVariable: PROMPT_RESULT

      - name: add-prompt-message
        from: prompt-executed
        to: prompt-message-added
        when: onEntry
        call:
          - tool: llm_addPromptResponseMessage

      - name: extract-tags
        from: prompt-message-added
        to: tags-extracted
        when: onEntry
        call:
          - tool: llm_extractResponseTags
            exportVariable: TAGS

      - name: ParseResponse
        from: tags-extracted
        to: response-parsed
        when: onEntry
        call:
          - tool: llm_parseResponseOutputSection
            exportVariable: PARSED_RESPONSE

      - name: create-document
        from: response-parsed
        to: document-created
        when: onEntry
        call:
          - tool: llm_createDocumentFromParsedResponse
            exportVariable: DOCUMENT_DRAFT

      - name: chat
        from: document-created
        to: messages-prepared
        when: manual
        call:
          - tool: core_createChatMessage
            exportVariable: CHAT_MESSAGE

      - name: confirm
        from: document-created
        to: confirmed
        when: |
          ${{ (workflow.options.autoConfirm && !workflow.history.includes('unlock')) ? 'onEntry' : 'manual' }}
        call:
          - tool: llm_confirmDocument
            exportVariable: CONFIRMED_DOCUMENT

      - name: finish
        from: confirmed
        to: end
        when: onEntry
      - name: unlock
        from: end
        to: document-created
        when: manual