workflows:
  - name: core_userInputTemplate
    type: stateMachine
    transitions:
      - name: start
        from: start
        to: started
        when: onEntry
      - name: request-form
        from: started
        to: waiting-for-user
        when: onEntry
        call:
          - tool: core_createDocument
            arguments:
              document: ${ workflow.options.document }
      - name: response
        from: waiting-for-user
        to: received
        when: manual
        call:
          - tool: core_createDocument
            arguments:
              document: ${ workflow.options.document }
              content: ${ transition.payload }
      - name: finish
        from: received
        to: end
        when: onEntry
      - name: unlock
        from: end
        to: waiting-for-user
        when: manual
