workflowTemplates:
  - name: core/userInputTemplate
    type: stateMachine
    transitions:
      - name: start
        from: start
        to: started
        when: onEntry
      - name: request-form
        from: started
        to: waiting-for-user
        when: onEntry
        call:
          - tool: core/createTemplateDocument
      - name: response
        from: waiting-for-user
        to: received
        when: manual
        call:
          - tool: core/createTemplateDocumentUserUpdate
      - name: finish
        from: received
        to: complete
        when: onEntry
      - name: unlock
        from: complete
        to: waiting-for-user
        when: manual
