# Include required core tools
include:
  - core/tools/create-chat-message.yaml
  - core/tools/create-response.yaml
  - core/tools/create-document.yaml

# Create a minimal root pipeline which executes the custom workflow
pipelines:
  - name: meeting_notes_tutorial
    title: "Tutorial 1: Meeting Notes Summarizer"
    workspace: examples
    type: root
    sequence:
      - workflow: meeting_notes_summarizer

# Create the workflow with interactive user input
workflows:
  - name: meeting_notes_summarizer
    title: "Meeting Notes Summarizer"
    type: stateMachine
    transitions:

      # First transition: Display the input form
      - name: render_meeting_notes_form
        from: start
        to: waiting_for_response
        call:
          - tool: create_document
            arguments:
              document: meeting_notes

      # Second transition: Capture user input (manual trigger)
      - name: create_user_response
        from: waiting_for_response
        to: user_response_created
        when: manual
        call:
          - tool: create_response
            arguments:
              document: meeting_notes
            as: USER_INPUT

      # Third transition: Process the notes and create summary
      - name: process_meeting_notes
        from: user_response_created
        to: meeting_notes_summarized
        call:
          - tool: llm_create_notes_summary
            arguments:
              raw_notes: ${ USER_INPUT.content.text }
            as: SUMMARY_RESULT

          - tool: create_chat_message
            arguments:
              role: ${ SUMMARY_RESULT.response.data.role }
              content: ${ SUMMARY_RESULT.response.data.content }

# Create the custom LLM tool for summarization
tools:
  - name: llm_create_notes_summary
    parameters:
      type: object
      properties:
        raw_notes:
          type: string
      required:
        - raw_notes
      additionalProperties: false
    execute:
      - handler: ChatCompletionsHandler
        arguments:
          llm:
            envApiKey: OPENAI_KEY
            model: gpt-4o
          messages:
            - role: system
              content: |
                You are a meeting notes summarizer. Transform these raw notes into a clear summary.
                
                Raw Notes: {{ arguments.raw_notes }}
                
                Create a summary with:
                
                **Decisions:**
                - What was decided
                
                **Action Items:**
                - Who needs to do what

# Define the document structure and UI
documents:
  - name: meeting_notes
    schema:
      type: object
      properties:
        text:
          type: string
    ui:
      properties:
        text:
          widget: textarea
      buttons:
        - transition: create_user_response
          label: "Submit"
    content:
      text: |
        budget: need 2 cut costs sarah said
        hire new person?? --> marketing
        vendor pricing - follow up needed by anna
        mike's project delayed again. deadline moved - when??? next month maybe
        client wants faster delivery but budget tight. can we do it?