workflows:
  - name: examples_toolCallSequence_workflow
    title: "Tool Call Sequence"
    type: tool
    sequence:
      - tool: core_createChatMessage
        arguments:
          role: assistant
          content: "Hello World!"

      - tool: core_createChatMessage
        arguments:
          role: user
          content: "Hi Assistant!"

pipelines:
  - name: examples_toolCallSequence
    title: "Tool Call Sequence Example"
    description: "This workflow demonstrates how to execute a simple sequence of tool calls in a workflow."
    workspace: examples
    entrypoint: examples_toolCallSequence_workflow

