tools:
  - name: llm_addPromptResponseMessage
    execute:
      service: createDocument
      arguments:
        document: core_internalMessage
        update:
          meta:
            data:
              prompt: ${ PROMPT_RESULT }
          content:
            role: assistant
            content: ${ PROMPT_RESULT.response.data }
