tools:
  - name: llm_confirmDocument
    execute:
      service: CreateDocumentService
      arguments:
        document: ${ workflow.options.document }
        update:
          meta:
            enableTransitions:
              - confirm
              - chat
            enableAtPlaces:
              - document-created
          content: ${ metadata.payload ?? DOCUMENT_DRAFT }