tools:
  - name: llm_createAssistantReasoningMessage
    execute:
      service: toolCall
      arguments:
        tool: core_createAssistantMessage
        options:
          message: ${ TAGS['Reasoning'] }