tools:
  - name: llm_createDocumentFromParsedResponse
    execute:
      service: CreateDocumentService
      arguments:
        document: ${{ workflow.options.document }}
        update:
          meta:
            enableAtPlaces:
              - document-created
          content: ${{ PARSED_RESPONSE }}