tools:
  - name: llm_createAssistantReasoningMessage
    execute:
      service: CreateDocumentService
      arguments:
        document: core_message
        update:
          content:
            role: assistant
            content: ${ TAGS['Reasoning'] }
