tools:
  - name: create_template
    parameters:
      type: object
      properties:
        document:
          type: string
    execute:
      handler: CreateOutputTemplateHandler
      arguments:
        document: ${ arguments.document }