tools:
  - name: llm_extractResponseTags
    execute:
      service: extractLlmResponseTags
      arguments:
        tags:
          - Reasoning
          - Output
        response: ${ PROMPT_RESULT.response.data }
