tools:
  - name: extract_tags
    parameters:
      type: object
      properties:
        source:
          type: any
        tags:
          type: array
          items:
            type: string
    execute:
      handler: ExtractResponseTagsHandler
      arguments:
        tags: ${ arguments.tags }
        response: ${ arguments.source }
