tools:
  - name: parse_template_response
    parameters:
      type: object
      properties:
        document:
          type: string
        response:
          type: string
    execute:
      handler: ParseResponseHandler
      arguments:
        document: ${ arguments.document }
        response: ${ arguments.response }