tools:
  - name: sayHelloWorld
    service: CreateDocumentService
    props:
      document: core/assistantMessage
      update:
        content:
          content: "Hello World"

workflows:
  - name: helloWorldWorkflow
    type: tool
    sequence:
      - call: sayHelloWorld

projects:
  - name: helloWorld
    title: "Hello World Example"
    workspace: default
    entrypoint: helloWorldWorkflow

workspaces:
  - name: default
    title: "Default"

