# File Includes
include:
  - core/documents/message.yaml

tools:
  - name: batch_create_messages
    parameters:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              content:
                type: object
                properties:
                  content:
                    type: 'string'
                  role:
                    type: string
                  tool_call_id:
                    type: 'string'
                  meta:
                    type: object
                    properties:
                      level:
                        type: string
                      invalidate:
                        type: boolean
                    additionalProperties: false
                additionalProperties: false
            required:
              - content
            additionalProperties: false
      required:
        - items
      additionalProperties: false
    execute:
      service: BatchCreateDocumentsService
      arguments:
        document: message
        items: ${ arguments.items }
