tools:
  - name: core_createChatMessage
    execute:
      service: CreateDocumentService
      arguments:
        document: core_message
        update:
          content:
            role: user
            content: ${ metadata.payload.message }