tools:
  - name: create_plain_message
    parameters:
      type: object
      properties:
        content:
          type: string
        title:
          type: string
      required:
        - content
      additionalProperties: false
    execute:
      service: CreateDocumentService
      arguments:
        document: plain_message
        update:
          content:
            title: ${ arguments.title }
            content: ${ arguments.content }
