tools:
  - name: core_createErrorMessage
    execute:
      service: createDocument
      arguments:
        document: core_assistantMessage
        update:
          content:
            role: assistant
            content: ${ workflow.options.message }