tools:
  - name: core_createDocument
    execute:
      service: CreateDocumentService
      arguments:
        document: ${ arguments.document }
        update:
          content: ${ arguments.content }