tools:
  - name: core_createErrorMessage
    execute:
      service: CreateDocumentService
      arguments:
        document: core_message
        update:
          content:
            role: assistant
            content: ${ workflow.options.message }