tools:
  - name: core_createErrorMessage
    parameters:
      type: object
      properties:
        message:
          type: string
      required:
        - message
      additionalItems: false
    execute:
      service: CreateDocumentService
      arguments:
        document: core_errorMessage
        update:
          content:
            message: ${ arguments.message }
