tools:
  - name: core/createTemplateDocumentUserUpdate
    execute:
      service: createDocument
      arguments:
        document: ${ workflow.options.document }
        update:
          content: ${ workflow.payload }