# File Includes
include:
  - core/documents/message.yaml

# Tool Definitions
tools:

  # Create Message Tool
  - name: create_chat_message

    # Input Arguments Validation JSON Schema
    parameters:
      type: object
      properties:
        content:
          type: [ "string", "null" ]
        role:
          type: string
        tool_calls:
          type: array
        tool_call_id:
          type: string
        meta:
          type: object
          properties:
            level:
              type: string
            invalidate:
              type: boolean
          additionalProperties: false
      additionalProperties: false

    # Service Execution
    execute:

      # Service Name
      service: CreateDocumentService

      # Service Call Arguments
      arguments:

        # Document Template
        document: message

        # Update Properties
        update:
          content:
            role: ${ arguments.role }
            content: ${ arguments.content }
            tool_calls: ${ arguments.tool_calls }
          meta:
            level: ${ arguments.meta.level }
            invalidate: ${ arguments.meta.invalidate }