tools:
  - name: core_createMessage
    parameters:
      type: object
      properties:
        content:
          type: object
      required:
        - content
      additionalItems: false
    execute:
      service: CreateDocumentService
      arguments:
        document: core_message
        update:
          content: ${ arguments.content }
