tools:
  - name: core_createPlainMessage
    parameters:
      type: object
      properties:
        content:
          type: string
        title:
          type: string
      required:
        - content
      additionalItems: false
    execute:
      service: CreateDocumentService
      arguments:
        document: core_plainMessage
        update:
          content:
            title: ${ arguments.title }
            content: ${ arguments.content }
