tools:
  - name: core_createUserMessage
    execute:
      service: createDocument
      arguments:
        document: core_userMessage
        update:
          content:
            role: user
            content: ${ workflow.options.message }