# File Includes
include:
  - core/documents/error.yaml

tools:
  - name: create_error_message
    parameters:
      type: object
      properties:
        message:
          type: string
      required:
        - message
      additionalProperties: false
    execute:
      service: CreateDocumentService
      arguments:
        document: error_message
        update:
          content:
            message: ${ arguments.message }
