tools:
  - name: create_response
    parameters:
      type: object
      properties:
        document:
          type: string
      required:
        - document
      additionalProperties: false
    execute:
      handler: CreateDocumentHandler
      arguments:
        document: ${ arguments.document }
        update:
          content: ${ transition.payload }