tools:
  - name: core_createUserMessage
    parameters:
      type: object
      properties:
        message:
          type: string
      required:
        - message
      additionalItems: false
    execute:
      service: CreateDocumentService
      arguments:
        document: core_message
        update:
          content:
            role: user
            content: ${ arguments.message }