tools:
  - name: delegate_tool_calls
    parameters:
      type: object
      properties:
        toolCalls:
          type: array
      required:
        - toolCalls
      additionalProperties: false
    execute:
      handler: DelegateToolCallsHandler
      arguments:
        toolCalls: ${ arguments.toolCalls }