tools:
  - name: load_document
    parameters:
      type: object
      properties:
        where:
          type: object
          # todo
        orderBy:
          type: object
          # todo
        getMany:
          type: boolean
        take:
          type: number
        skip:
          type: number
        isDependency:
          type: boolean
        global:
          type: boolean
        strictMode:
          type: boolean
      required:
        - where
      additionalProperties: false
    execute:
      service: LoadDocumentService
      arguments:
        where: ${ arguments.where }
        orderBy: ${ arguments.orderBy }
        getMany: ${ arguments.getMany }
        take: ${ arguments.take }
        isDependency: ${ arguments.isDependency }
        isGlobal: ${ arguments.isGlobal }
        strictMode: ${ arguments.strictMode }