tools:
  - name: update_document
    parameters:
      type: object
      properties:
        id:
          type: string
        content:
          type: any
      required:
        - id
        - content
      additionalProperties: false
    execute:
      handler: UpdateDocumentHandler
      arguments:
        id: ${ arguments.id }
        update:
          content: ${ arguments.content }