documents:
  - name: error_message
    tags:
      - error
    ui:
      widget: error-message
    schema:
      type: object
      properties: 
        message:
          type: string
      additionalProperties: false
    meta:
      invalidate: false
      level: error
