documents:
  - name: core/loadingMessage
    ui:
      widget: chat-message
    schema:
      type: object
    content:
      role: assistant
      content: "Generating answer..."
      animation: loading