documents:
  - name: message
    tags:
      - message
    ui:
      widget: chat-message
    schema:
      type: object
      properties: 
        role:
          type: string
        content:
          type: [ "string", "null" ]
        tool_calls:
          type: array
        tool_call_id:
          type: [ "string", "null" ]
      additionalProperties: false
    meta:
      invalidate: false
      level: info
