documents:
  - name: message
    tags:
      - message
    ui:
      widget: chat-message
    schema:
      type: object
      properties: 
        role:
          type: string
        content:
          type: 'string'
        tool_calls:
          type: 'array'
      additionalProperties: false
    meta:
      invalidate: false
      level: info
