documents:
  - name: plain_message
    ui:
      widget: plain-message
    schema:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
      additionalProperties: false
    meta:
      level: info
      invalidate: false
    content:
      title: "Text"
      content: ""