include:
  - core/tools/create-chat-message.yaml
  - core/tools/create-plain-message.yaml
  - core/tools/create-document.yaml
  - core/tools/create-mock.yaml

documents:
  - name: user_input_form
    schema:
      type: object
      properties:
        text:
          type: string
    ui:
      properties:
        text:
          widget: textarea
      buttons:
        - transition: add_user_input
          label: "Submit"
    content:
      text: ""

workflows:
  - name: predefined_workflow_workflow
    title: "Analyse and Improve Text"
    type: stateMachine
    transitions:

      - name: request_user_input
        from: start
        to: waiting_for_user
        call:
          - tool: create_chat_message
            arguments:
              role: assistant
              content: "This simple workflow example takes user-provided text, analyzes it for issues, and then improves it based on the analysis."
          - tool: create_document
            arguments:
              document: user_input_form
              content:
                text: "Me and my friend goes to the store yesterday we buy some stuff for the party but we forgot to get drinks so we had to went back again it was really annoying."

      - name: add_user_input
        from: waiting_for_user
        to: user_input_added
        when: manual
        call:
          - tool: create_document
            arguments:
              document: user_input_form
              content: ${ transition.payload }
            as: USER_INPUT_DOCUMENT

      - name: analyse
        from: user_input_added
        to: input_analysed
        call:
          - tool: analyse_text
            as: ANALYSIS

      - name: add_analysis
        from: input_analysed
        to: analysis_added
        call:
          - tool: create_mock
            arguments:
              input: ${ ANALYSIS.response.data }
          - tool: create_plain_message
            arguments:
              title: "Analysis"
              content: ${ ANALYSIS.response.data.content }

      - name: improve
        from: analysis_added
        to: improved
        call:
          - tool: improve_text
            as: IMPROVED_TEXT

      - name: add_improved_text
        from: improved
        to: improved_text_added
        call:
          - tool: create_mock
            arguments:
              input: ${ ANALYSIS.response.data }
          - tool: create_plain_message
            arguments:
              title: "Improved Text"
              content: ${ IMPROVED_TEXT.response.data.content }

tools:
  - name: analyse_text
    execute:
      - handler: ChatCompletionsHandler
        arguments:
          llm:
            envApiKey: OPENAI_KEY
            model: gpt-4o
          messages:
            - role: system
              content: |
                You are a content analyst. Analyze the provided text and identify:
                1. Grammar and spelling issues
                2. Clarity problems
                3. Tone inconsistencies
                4. Structural improvements needed
                
                Provide your analysis in a structured format with specific recommendations.
            - role: user
              content: |
                Please analyze this text: 
                {{ USER_INPUT_DOCUMENT.content.text }}

  - name: improve_text
    execute:
      - handler: ChatCompletionsHandler
        arguments:
          llm:
            envApiKey: OPENAI_KEY
            model: gpt-4o
          messages:
            - role: system
              content: |
                You are a professional editor. Based on the analysis provided, improve the original text by:
                1. Fixing grammar and spelling errors
                2. Enhancing clarity and readability
                3. Maintaining the original meaning and intent
                4. Improving overall structure and flow
                
                Return only the improved version of the text.
            - role: user
              content: |
                Original text:
                {{ USER_INPUT_DOCUMENT.content.text }}
  
                Analysis and recommendations:
                {{ ANALYSIS.response.data }}
                  
                Please provide an improved version of the original text based on this analysis.

pipelines:
  - name: predefined_workflow_example
    title: "LLM Example 3: Predefined Workflow"
    workspace: examples
    type: root
    sequence:
      - workflow: predefined_workflow_workflow
