snippets:
  - name: reasonOutputReflectionTemplate
    value: |
      <Reasoning>
      any reasoning and thoughts to prepare your answer (optional)
      </Reasoning>
      <Output>
      ${ OUTPUT_TEMPLATE }
      </Output>
      <Reflection>
      Any additional information (optional)
      </Reflection>